/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_STAR = 1,
  anon_sym_COLON = 2,
  sym__invalid_symbol = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_AT = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_DASH_GT = 9,
  sym_null_expr = 10,
  sym_copy_expr = 11,
  sym_sig_expr = 12,
  sym_hash_expr = 13,
  anon_sym_DASH_LT_DASH = 14,
  anon_sym_PLUS_LT_DASH = 15,
  anon_sym_DASH_LT_PLUS = 16,
  anon_sym_PLUS_LT_PLUS = 17,
  anon_sym_DASH_TILDE_DASH = 18,
  anon_sym_PLUS_TILDE_DASH = 19,
  anon_sym_DASH_TILDE_PLUS = 20,
  anon_sym_PLUS_TILDE_PLUS = 21,
  sym_symbol = 22,
  sym_source_file = 23,
  sym_error_symbol = 24,
  sym_copland = 25,
  sym_place = 26,
  sym_phrase = 27,
  sym_at_expr = 28,
  sym_branch_expr = 29,
  sym_seq_expr = 30,
  sym_measurement = 31,
  sym_branch_op = 32,
  aux_sym_source_file_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STAR] = "*",
  [anon_sym_COLON] = ":",
  [sym__invalid_symbol] = "ERROR",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_AT] = "@",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH_GT] = "->",
  [sym_null_expr] = "null_expr",
  [sym_copy_expr] = "copy_expr",
  [sym_sig_expr] = "sig_expr",
  [sym_hash_expr] = "hash_expr",
  [anon_sym_DASH_LT_DASH] = "-<-",
  [anon_sym_PLUS_LT_DASH] = "+<-",
  [anon_sym_DASH_LT_PLUS] = "-<+",
  [anon_sym_PLUS_LT_PLUS] = "+<+",
  [anon_sym_DASH_TILDE_DASH] = "-~-",
  [anon_sym_PLUS_TILDE_DASH] = "+~-",
  [anon_sym_DASH_TILDE_PLUS] = "-~+",
  [anon_sym_PLUS_TILDE_PLUS] = "+~+",
  [sym_symbol] = "symbol",
  [sym_source_file] = "source_file",
  [sym_error_symbol] = "error_symbol",
  [sym_copland] = "copland",
  [sym_place] = "place",
  [sym_phrase] = "phrase",
  [sym_at_expr] = "at_expr",
  [sym_branch_expr] = "branch_expr",
  [sym_seq_expr] = "seq_expr",
  [sym_measurement] = "measurement",
  [sym_branch_op] = "branch_op",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__invalid_symbol] = sym__invalid_symbol,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_null_expr] = sym_null_expr,
  [sym_copy_expr] = sym_copy_expr,
  [sym_sig_expr] = sym_sig_expr,
  [sym_hash_expr] = sym_hash_expr,
  [anon_sym_DASH_LT_DASH] = anon_sym_DASH_LT_DASH,
  [anon_sym_PLUS_LT_DASH] = anon_sym_PLUS_LT_DASH,
  [anon_sym_DASH_LT_PLUS] = anon_sym_DASH_LT_PLUS,
  [anon_sym_PLUS_LT_PLUS] = anon_sym_PLUS_LT_PLUS,
  [anon_sym_DASH_TILDE_DASH] = anon_sym_DASH_TILDE_DASH,
  [anon_sym_PLUS_TILDE_DASH] = anon_sym_PLUS_TILDE_DASH,
  [anon_sym_DASH_TILDE_PLUS] = anon_sym_DASH_TILDE_PLUS,
  [anon_sym_PLUS_TILDE_PLUS] = anon_sym_PLUS_TILDE_PLUS,
  [sym_symbol] = sym_symbol,
  [sym_source_file] = sym_source_file,
  [sym_error_symbol] = sym_error_symbol,
  [sym_copland] = sym_copland,
  [sym_place] = sym_place,
  [sym_phrase] = sym_phrase,
  [sym_at_expr] = sym_at_expr,
  [sym_branch_expr] = sym_branch_expr,
  [sym_seq_expr] = sym_seq_expr,
  [sym_measurement] = sym_measurement,
  [sym_branch_op] = sym_branch_op,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__invalid_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_null_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_copy_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_sig_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_expr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_LT_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_LT_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_TILDE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_TILDE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_TILDE_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_TILDE_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_error_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_copland] = {
    .visible = true,
    .named = true,
  },
  [sym_place] = {
    .visible = true,
    .named = true,
  },
  [sym_phrase] = {
    .visible = true,
    .named = true,
  },
  [sym_at_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_seq_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_measurement] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_op] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_branchLeft = 1,
  field_branchRight = 2,
  field_initial_place = 3,
  field_op = 4,
  field_phrase = 5,
  field_place = 6,
  field_probe = 7,
  field_seqLeft = 8,
  field_seqRight = 9,
  field_target = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_branchLeft] = "branchLeft",
  [field_branchRight] = "branchRight",
  [field_initial_place] = "initial_place",
  [field_op] = "op",
  [field_phrase] = "phrase",
  [field_place] = "place",
  [field_probe] = "probe",
  [field_seqLeft] = "seqLeft",
  [field_seqRight] = "seqRight",
  [field_target] = "target",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 2},
  [5] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_place, 1},
    {field_probe, 0},
    {field_target, 2},
  [3] =
    {field_seqLeft, 0},
    {field_seqRight, 2},
  [5] =
    {field_branchLeft, 0},
    {field_branchRight, 2},
    {field_op, 1},
  [8] =
    {field_initial_place, 1},
    {field_phrase, 3},
  [10] =
    {field_phrase, 3},
    {field_place, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '!', 25,
        '#', 26,
        '(', 16,
        ')', 17,
        '*', 13,
        '+', 7,
        '-', 8,
        ':', 14,
        '@', 18,
        '[', 19,
        ']', 20,
        '_', 24,
        '{', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '#') ADVANCE(26);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead == '_') ADVANCE(23);
      if (lookahead == '{') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '#') ADVANCE(26);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead == '{') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '+') ADVANCE(34);
      if (lookahead == '-') ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == '-') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == '-') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '~') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead == '~') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '!', 25,
        '#', 26,
        '(', 16,
        ')', 17,
        '*', 13,
        '+', 7,
        '-', 8,
        ':', 14,
        '@', 18,
        '[', 19,
        ']', 20,
        '_', 10,
        '{', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__invalid_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_null_expr);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_copy_expr);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_copy_expr);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_sig_expr);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_hash_expr);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH_LT_DASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS_LT_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_LT_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS_LT_PLUS);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH_TILDE_DASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PLUS_TILDE_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH_TILDE_PLUS);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS_TILDE_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym__invalid_symbol] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_null_expr] = ACTIONS(1),
    [sym_copy_expr] = ACTIONS(1),
    [sym_sig_expr] = ACTIONS(1),
    [sym_hash_expr] = ACTIONS(1),
    [anon_sym_DASH_LT_DASH] = ACTIONS(1),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(1),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(1),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(1),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(1),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym_error_symbol] = STATE(11),
    [sym_copland] = STATE(11),
    [sym_phrase] = STATE(9),
    [sym_at_expr] = STATE(5),
    [sym_branch_expr] = STATE(5),
    [sym_seq_expr] = STATE(5),
    [sym_measurement] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(5),
    [sym__invalid_symbol] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [sym_null_expr] = ACTIONS(13),
    [sym_copy_expr] = ACTIONS(15),
    [sym_sig_expr] = ACTIONS(13),
    [sym_hash_expr] = ACTIONS(13),
    [sym_symbol] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym_place] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(19),
    [sym__invalid_symbol] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [sym_null_expr] = ACTIONS(19),
    [sym_copy_expr] = ACTIONS(21),
    [sym_sig_expr] = ACTIONS(19),
    [sym_hash_expr] = ACTIONS(19),
    [anon_sym_DASH_LT_DASH] = ACTIONS(19),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(19),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(19),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(19),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(19),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(19),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(19),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(19),
    [sym_symbol] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_branch_op] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [sym__invalid_symbol] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_DASH_GT] = ACTIONS(27),
    [sym_null_expr] = ACTIONS(25),
    [sym_copy_expr] = ACTIONS(29),
    [sym_sig_expr] = ACTIONS(25),
    [sym_hash_expr] = ACTIONS(25),
    [anon_sym_DASH_LT_DASH] = ACTIONS(25),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(25),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(25),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(25),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(25),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(25),
    [sym_symbol] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym_branch_op] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(31),
    [sym__invalid_symbol] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_AT] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_DASH_GT] = ACTIONS(27),
    [sym_null_expr] = ACTIONS(31),
    [sym_copy_expr] = ACTIONS(33),
    [sym_sig_expr] = ACTIONS(31),
    [sym_hash_expr] = ACTIONS(31),
    [anon_sym_DASH_LT_DASH] = ACTIONS(31),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(31),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(31),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(31),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(31),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(31),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(31),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(31),
    [sym_symbol] = ACTIONS(31),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(19),
    [sym__invalid_symbol] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(19),
    [anon_sym_RBRACK] = ACTIONS(19),
    [anon_sym_DASH_GT] = ACTIONS(19),
    [sym_null_expr] = ACTIONS(19),
    [sym_copy_expr] = ACTIONS(21),
    [sym_sig_expr] = ACTIONS(19),
    [sym_hash_expr] = ACTIONS(19),
    [anon_sym_DASH_LT_DASH] = ACTIONS(19),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(19),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(19),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(19),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(19),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(19),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(19),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(19),
    [sym_symbol] = ACTIONS(19),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(35),
    [sym__invalid_symbol] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_AT] = ACTIONS(35),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_DASH_GT] = ACTIONS(35),
    [sym_null_expr] = ACTIONS(35),
    [sym_copy_expr] = ACTIONS(37),
    [sym_sig_expr] = ACTIONS(35),
    [sym_hash_expr] = ACTIONS(35),
    [anon_sym_DASH_LT_DASH] = ACTIONS(35),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(35),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(35),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(35),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(35),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(35),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(35),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(35),
    [sym_symbol] = ACTIONS(35),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [anon_sym_STAR] = ACTIONS(39),
    [sym__invalid_symbol] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_DASH_GT] = ACTIONS(39),
    [sym_null_expr] = ACTIONS(39),
    [sym_copy_expr] = ACTIONS(41),
    [sym_sig_expr] = ACTIONS(39),
    [sym_hash_expr] = ACTIONS(39),
    [anon_sym_DASH_LT_DASH] = ACTIONS(39),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(39),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(39),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(39),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(39),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(39),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(39),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(39),
    [sym_symbol] = ACTIONS(39),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [sym__invalid_symbol] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_AT] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_DASH_GT] = ACTIONS(43),
    [sym_null_expr] = ACTIONS(43),
    [sym_copy_expr] = ACTIONS(45),
    [sym_sig_expr] = ACTIONS(43),
    [sym_hash_expr] = ACTIONS(43),
    [anon_sym_DASH_LT_DASH] = ACTIONS(43),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(43),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(43),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(43),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(43),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(43),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(43),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(43),
    [sym_symbol] = ACTIONS(43),
  },
  [STATE(9)] = {
    [sym_branch_op] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(47),
    [sym__invalid_symbol] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_AT] = ACTIONS(47),
    [anon_sym_DASH_GT] = ACTIONS(27),
    [sym_null_expr] = ACTIONS(47),
    [sym_copy_expr] = ACTIONS(49),
    [sym_sig_expr] = ACTIONS(47),
    [sym_hash_expr] = ACTIONS(47),
    [anon_sym_DASH_LT_DASH] = ACTIONS(51),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(51),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(51),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(51),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(51),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(51),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(51),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(51),
    [sym_symbol] = ACTIONS(47),
  },
  [STATE(10)] = {
    [sym_branch_op] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(53),
    [sym__invalid_symbol] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_AT] = ACTIONS(53),
    [anon_sym_DASH_GT] = ACTIONS(27),
    [sym_null_expr] = ACTIONS(53),
    [sym_copy_expr] = ACTIONS(55),
    [sym_sig_expr] = ACTIONS(53),
    [sym_hash_expr] = ACTIONS(53),
    [anon_sym_DASH_LT_DASH] = ACTIONS(51),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(51),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(51),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(51),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(51),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(51),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(51),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(51),
    [sym_symbol] = ACTIONS(53),
  },
  [STATE(11)] = {
    [sym_error_symbol] = STATE(12),
    [sym_copland] = STATE(12),
    [sym_phrase] = STATE(9),
    [sym_at_expr] = STATE(5),
    [sym_branch_expr] = STATE(5),
    [sym_seq_expr] = STATE(5),
    [sym_measurement] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(5),
    [sym__invalid_symbol] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [sym_null_expr] = ACTIONS(13),
    [sym_copy_expr] = ACTIONS(15),
    [sym_sig_expr] = ACTIONS(13),
    [sym_hash_expr] = ACTIONS(13),
    [sym_symbol] = ACTIONS(17),
  },
  [STATE(12)] = {
    [sym_error_symbol] = STATE(12),
    [sym_copland] = STATE(12),
    [sym_phrase] = STATE(9),
    [sym_at_expr] = STATE(5),
    [sym_branch_expr] = STATE(5),
    [sym_seq_expr] = STATE(5),
    [sym_measurement] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(61),
    [sym__invalid_symbol] = ACTIONS(64),
    [anon_sym_LPAREN] = ACTIONS(67),
    [anon_sym_AT] = ACTIONS(70),
    [sym_null_expr] = ACTIONS(73),
    [sym_copy_expr] = ACTIONS(76),
    [sym_sig_expr] = ACTIONS(73),
    [sym_hash_expr] = ACTIONS(73),
    [sym_symbol] = ACTIONS(79),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_symbol,
    STATE(18), 1,
      sym_phrase,
    ACTIONS(13), 4,
      sym_null_expr,
      sym_copy_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(5), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [25] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_symbol,
    STATE(10), 1,
      sym_phrase,
    ACTIONS(13), 4,
      sym_null_expr,
      sym_copy_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(5), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [50] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_symbol,
    STATE(4), 1,
      sym_phrase,
    ACTIONS(13), 4,
      sym_null_expr,
      sym_copy_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(5), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [75] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_symbol,
    STATE(19), 1,
      sym_phrase,
    ACTIONS(13), 4,
      sym_null_expr,
      sym_copy_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(5), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [100] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_symbol,
    STATE(3), 1,
      sym_phrase,
    ACTIONS(13), 4,
      sym_null_expr,
      sym_copy_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(5), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [125] = 4,
    ACTIONS(27), 1,
      anon_sym_DASH_GT,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      sym_branch_op,
    ACTIONS(51), 8,
      anon_sym_DASH_LT_DASH,
      anon_sym_PLUS_LT_DASH,
      anon_sym_DASH_LT_PLUS,
      anon_sym_PLUS_LT_PLUS,
      anon_sym_DASH_TILDE_DASH,
      anon_sym_PLUS_TILDE_DASH,
      anon_sym_DASH_TILDE_PLUS,
      anon_sym_PLUS_TILDE_PLUS,
  [145] = 4,
    ACTIONS(27), 1,
      anon_sym_DASH_GT,
    ACTIONS(84), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      sym_branch_op,
    ACTIONS(51), 8,
      anon_sym_DASH_LT_DASH,
      anon_sym_PLUS_LT_DASH,
      anon_sym_DASH_LT_PLUS,
      anon_sym_PLUS_LT_PLUS,
      anon_sym_DASH_TILDE_DASH,
      anon_sym_PLUS_TILDE_DASH,
      anon_sym_DASH_TILDE_PLUS,
      anon_sym_PLUS_TILDE_PLUS,
  [165] = 2,
    ACTIONS(88), 1,
      sym_copy_expr,
    ACTIONS(86), 9,
      ts_builtin_sym_end,
      anon_sym_STAR,
      sym__invalid_symbol,
      anon_sym_LPAREN,
      anon_sym_AT,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
      sym_symbol,
  [180] = 1,
    ACTIONS(90), 7,
      anon_sym_LPAREN,
      anon_sym_AT,
      sym_null_expr,
      sym_copy_expr,
      sym_sig_expr,
      sym_hash_expr,
      sym_symbol,
  [190] = 1,
    ACTIONS(92), 3,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_symbol,
  [196] = 2,
    ACTIONS(23), 1,
      sym_symbol,
    STATE(26), 1,
      sym_place,
  [203] = 2,
    ACTIONS(23), 1,
      sym_symbol,
    STATE(28), 1,
      sym_place,
  [210] = 1,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
  [214] = 1,
    ACTIONS(96), 1,
      anon_sym_COLON,
  [218] = 1,
    ACTIONS(98), 1,
      sym_symbol,
  [222] = 1,
    ACTIONS(100), 1,
      anon_sym_LBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 25,
  [SMALL_STATE(15)] = 50,
  [SMALL_STATE(16)] = 75,
  [SMALL_STATE(17)] = 100,
  [SMALL_STATE(18)] = 125,
  [SMALL_STATE(19)] = 145,
  [SMALL_STATE(20)] = 165,
  [SMALL_STATE(21)] = 180,
  [SMALL_STATE(22)] = 190,
  [SMALL_STATE(23)] = 196,
  [SMALL_STATE(24)] = 203,
  [SMALL_STATE(25)] = 210,
  [SMALL_STATE(26)] = 214,
  [SMALL_STATE(27)] = 218,
  [SMALL_STATE(28)] = 222,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_phrase, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_expr, 3, 0, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch_expr, 3, 0, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seq_expr, 3, 0, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_seq_expr, 3, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_measurement, 3, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_measurement, 3, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_phrase, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_at_expr, 5, 0, 5),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_at_expr, 5, 0, 5),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copland, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_copland, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copland, 4, 0, 4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_copland, 4, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error_symbol, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_error_symbol, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_op, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_copland(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "copland",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
