/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_STAR = 1,
  anon_sym_COLON = 2,
  anon_sym_COMMA = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_AT = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_DASH_GT = 9,
  sym_null_expr = 10,
  sym_copy_expr = 11,
  sym_sig_expr = 12,
  sym_hash_expr = 13,
  anon_sym_DASH_LT_DASH = 14,
  anon_sym_PLUS_LT_DASH = 15,
  anon_sym_DASH_LT_PLUS = 16,
  anon_sym_PLUS_LT_PLUS = 17,
  anon_sym_DASH_TILDE_DASH = 18,
  anon_sym_PLUS_TILDE_DASH = 19,
  anon_sym_DASH_TILDE_PLUS = 20,
  anon_sym_PLUS_TILDE_PLUS = 21,
  sym_symbol = 22,
  sym_source_file = 23,
  sym_copland = 24,
  sym_places = 25,
  sym_place = 26,
  sym_phrase = 27,
  sym_at_expr = 28,
  sym_branch_expr = 29,
  sym_seq_expr = 30,
  sym_measurement = 31,
  sym_branch_op = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_places_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STAR] = "*",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_AT] = "@",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH_GT] = "->",
  [sym_null_expr] = "null_expr",
  [sym_copy_expr] = "copy_expr",
  [sym_sig_expr] = "sig_expr",
  [sym_hash_expr] = "hash_expr",
  [anon_sym_DASH_LT_DASH] = "-<-",
  [anon_sym_PLUS_LT_DASH] = "+<-",
  [anon_sym_DASH_LT_PLUS] = "-<+",
  [anon_sym_PLUS_LT_PLUS] = "+<+",
  [anon_sym_DASH_TILDE_DASH] = "-~-",
  [anon_sym_PLUS_TILDE_DASH] = "+~-",
  [anon_sym_DASH_TILDE_PLUS] = "-~+",
  [anon_sym_PLUS_TILDE_PLUS] = "+~+",
  [sym_symbol] = "symbol",
  [sym_source_file] = "source_file",
  [sym_copland] = "copland",
  [sym_places] = "places",
  [sym_place] = "place",
  [sym_phrase] = "phrase",
  [sym_at_expr] = "at_expr",
  [sym_branch_expr] = "branch_expr",
  [sym_seq_expr] = "seq_expr",
  [sym_measurement] = "measurement",
  [sym_branch_op] = "branch_op",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_places_repeat1] = "places_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_null_expr] = sym_null_expr,
  [sym_copy_expr] = sym_copy_expr,
  [sym_sig_expr] = sym_sig_expr,
  [sym_hash_expr] = sym_hash_expr,
  [anon_sym_DASH_LT_DASH] = anon_sym_DASH_LT_DASH,
  [anon_sym_PLUS_LT_DASH] = anon_sym_PLUS_LT_DASH,
  [anon_sym_DASH_LT_PLUS] = anon_sym_DASH_LT_PLUS,
  [anon_sym_PLUS_LT_PLUS] = anon_sym_PLUS_LT_PLUS,
  [anon_sym_DASH_TILDE_DASH] = anon_sym_DASH_TILDE_DASH,
  [anon_sym_PLUS_TILDE_DASH] = anon_sym_PLUS_TILDE_DASH,
  [anon_sym_DASH_TILDE_PLUS] = anon_sym_DASH_TILDE_PLUS,
  [anon_sym_PLUS_TILDE_PLUS] = anon_sym_PLUS_TILDE_PLUS,
  [sym_symbol] = sym_symbol,
  [sym_source_file] = sym_source_file,
  [sym_copland] = sym_copland,
  [sym_places] = sym_places,
  [sym_place] = sym_place,
  [sym_phrase] = sym_phrase,
  [sym_at_expr] = sym_at_expr,
  [sym_branch_expr] = sym_branch_expr,
  [sym_seq_expr] = sym_seq_expr,
  [sym_measurement] = sym_measurement,
  [sym_branch_op] = sym_branch_op,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_places_repeat1] = aux_sym_places_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_null_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_copy_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_sig_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_expr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_LT_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_LT_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_TILDE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_TILDE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_TILDE_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_TILDE_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_copland] = {
    .visible = true,
    .named = true,
  },
  [sym_places] = {
    .visible = true,
    .named = true,
  },
  [sym_place] = {
    .visible = true,
    .named = true,
  },
  [sym_phrase] = {
    .visible = true,
    .named = true,
  },
  [sym_at_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_seq_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_measurement] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_op] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_places_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_branchLeft = 1,
  field_branchRight = 2,
  field_initial_place = 3,
  field_op = 4,
  field_phrase = 5,
  field_place = 6,
  field_probe = 7,
  field_seqLeft = 8,
  field_seqRight = 9,
  field_target = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_branchLeft] = "branchLeft",
  [field_branchRight] = "branchRight",
  [field_initial_place] = "initial_place",
  [field_op] = "op",
  [field_phrase] = "phrase",
  [field_place] = "place",
  [field_probe] = "probe",
  [field_seqLeft] = "seqLeft",
  [field_seqRight] = "seqRight",
  [field_target] = "target",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 2},
  [5] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_place, 1},
    {field_probe, 0},
    {field_target, 2},
  [3] =
    {field_seqLeft, 0},
    {field_seqRight, 2},
  [5] =
    {field_branchLeft, 0},
    {field_branchRight, 2},
    {field_op, 1},
  [8] =
    {field_initial_place, 1},
    {field_phrase, 3},
  [10] =
    {field_phrase, 3},
    {field_place, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 14,
  [18] = 18,
  [19] = 19,
  [20] = 15,
  [21] = 8,
  [22] = 10,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 21,
        '#', 22,
        '(', 13,
        ')', 14,
        '*', 10,
        '+', 6,
        ',', 12,
        '-', 7,
        ':', 11,
        '@', 15,
        '[', 16,
        ']', 17,
        '_', 20,
        '{', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '+') ADVANCE(6);
      if (lookahead == ',') ADVANCE(12);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '[') ADVANCE(16);
      if (lookahead == ']') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '+') ADVANCE(26);
      if (lookahead == '-') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(30);
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '+') ADVANCE(25);
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == '-') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(2);
      if (lookahead == '~') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == '>') ADVANCE(18);
      if (lookahead == '~') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(19);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_null_expr);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_copy_expr);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_sig_expr);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_hash_expr);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_LT_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PLUS_LT_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH_LT_PLUS);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PLUS_LT_PLUS);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH_TILDE_DASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS_TILDE_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_TILDE_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS_TILDE_PLUS);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_null_expr] = ACTIONS(1),
    [sym_copy_expr] = ACTIONS(1),
    [sym_sig_expr] = ACTIONS(1),
    [sym_hash_expr] = ACTIONS(1),
    [anon_sym_DASH_LT_DASH] = ACTIONS(1),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(1),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(1),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(1),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(1),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(37),
    [sym_copland] = STATE(12),
    [sym_phrase] = STATE(7),
    [sym_at_expr] = STATE(2),
    [sym_branch_expr] = STATE(2),
    [sym_seq_expr] = STATE(2),
    [sym_measurement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [sym_null_expr] = ACTIONS(11),
    [sym_copy_expr] = ACTIONS(13),
    [sym_sig_expr] = ACTIONS(11),
    [sym_hash_expr] = ACTIONS(11),
    [sym_symbol] = ACTIONS(15),
  },
  [STATE(2)] = {
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(17),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_null_expr] = ACTIONS(17),
    [sym_copy_expr] = ACTIONS(19),
    [sym_sig_expr] = ACTIONS(17),
    [sym_hash_expr] = ACTIONS(17),
    [anon_sym_DASH_LT_DASH] = ACTIONS(17),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(17),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(17),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(17),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(17),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(17),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(17),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(17),
    [sym_symbol] = ACTIONS(19),
  },
  [STATE(3)] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_AT] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [sym_null_expr] = ACTIONS(21),
    [sym_copy_expr] = ACTIONS(23),
    [sym_sig_expr] = ACTIONS(21),
    [sym_hash_expr] = ACTIONS(21),
    [anon_sym_DASH_LT_DASH] = ACTIONS(21),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(21),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(21),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(21),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(21),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(21),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(21),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(21),
    [sym_symbol] = ACTIONS(23),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_AT] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_DASH_GT] = ACTIONS(25),
    [sym_null_expr] = ACTIONS(25),
    [sym_copy_expr] = ACTIONS(27),
    [sym_sig_expr] = ACTIONS(25),
    [sym_hash_expr] = ACTIONS(25),
    [anon_sym_DASH_LT_DASH] = ACTIONS(25),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(25),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(25),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(25),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(25),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(25),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_AT] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(29),
    [anon_sym_DASH_GT] = ACTIONS(29),
    [sym_null_expr] = ACTIONS(29),
    [sym_copy_expr] = ACTIONS(31),
    [sym_sig_expr] = ACTIONS(29),
    [sym_hash_expr] = ACTIONS(29),
    [anon_sym_DASH_LT_DASH] = ACTIONS(29),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(29),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(29),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(29),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(29),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(29),
    [sym_symbol] = ACTIONS(31),
  },
  [STATE(6)] = {
    [sym_branch_op] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_AT] = ACTIONS(33),
    [anon_sym_DASH_GT] = ACTIONS(35),
    [sym_null_expr] = ACTIONS(33),
    [sym_copy_expr] = ACTIONS(37),
    [sym_sig_expr] = ACTIONS(33),
    [sym_hash_expr] = ACTIONS(33),
    [anon_sym_DASH_LT_DASH] = ACTIONS(39),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(39),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(39),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(39),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(39),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(39),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(39),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(39),
    [sym_symbol] = ACTIONS(37),
  },
  [STATE(7)] = {
    [sym_branch_op] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_AT] = ACTIONS(41),
    [anon_sym_DASH_GT] = ACTIONS(35),
    [sym_null_expr] = ACTIONS(41),
    [sym_copy_expr] = ACTIONS(43),
    [sym_sig_expr] = ACTIONS(41),
    [sym_hash_expr] = ACTIONS(41),
    [anon_sym_DASH_LT_DASH] = ACTIONS(39),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(39),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(39),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(39),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(39),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(39),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(39),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(39),
    [sym_symbol] = ACTIONS(43),
  },
  [STATE(8)] = {
    [sym_branch_op] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(45),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_AT] = ACTIONS(45),
    [anon_sym_DASH_GT] = ACTIONS(35),
    [sym_null_expr] = ACTIONS(45),
    [sym_copy_expr] = ACTIONS(47),
    [sym_sig_expr] = ACTIONS(45),
    [sym_hash_expr] = ACTIONS(45),
    [anon_sym_DASH_LT_DASH] = ACTIONS(45),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(45),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(45),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(45),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(45),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(45),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(45),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(45),
    [sym_symbol] = ACTIONS(47),
  },
  [STATE(9)] = {
    [sym_place] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(17),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_null_expr] = ACTIONS(17),
    [sym_copy_expr] = ACTIONS(19),
    [sym_sig_expr] = ACTIONS(17),
    [sym_hash_expr] = ACTIONS(17),
    [anon_sym_DASH_LT_DASH] = ACTIONS(17),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(17),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(17),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(17),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(17),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(17),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(17),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(17),
    [sym_symbol] = ACTIONS(49),
  },
  [STATE(10)] = {
    [sym_branch_op] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_AT] = ACTIONS(51),
    [anon_sym_DASH_GT] = ACTIONS(35),
    [sym_null_expr] = ACTIONS(51),
    [sym_copy_expr] = ACTIONS(53),
    [sym_sig_expr] = ACTIONS(51),
    [sym_hash_expr] = ACTIONS(51),
    [anon_sym_DASH_LT_DASH] = ACTIONS(51),
    [anon_sym_PLUS_LT_DASH] = ACTIONS(51),
    [anon_sym_DASH_LT_PLUS] = ACTIONS(51),
    [anon_sym_PLUS_LT_PLUS] = ACTIONS(51),
    [anon_sym_DASH_TILDE_DASH] = ACTIONS(51),
    [anon_sym_PLUS_TILDE_DASH] = ACTIONS(51),
    [anon_sym_DASH_TILDE_PLUS] = ACTIONS(51),
    [anon_sym_PLUS_TILDE_PLUS] = ACTIONS(51),
    [sym_symbol] = ACTIONS(53),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_STAR,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_AT,
    ACTIONS(69), 1,
      sym_copy_expr,
    ACTIONS(72), 1,
      sym_symbol,
    STATE(7), 1,
      sym_phrase,
    STATE(11), 2,
      sym_copland,
      aux_sym_source_file_repeat1,
    ACTIONS(66), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [37] = 10,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(15), 1,
      sym_symbol,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_phrase,
    STATE(11), 2,
      sym_copland,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [74] = 3,
    ACTIONS(77), 1,
      sym_symbol,
    STATE(35), 1,
      sym_place,
    ACTIONS(17), 11,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_DASH_GT,
      anon_sym_DASH_LT_DASH,
      anon_sym_PLUS_LT_DASH,
      anon_sym_DASH_LT_PLUS,
      anon_sym_PLUS_LT_PLUS,
      anon_sym_DASH_TILDE_DASH,
      anon_sym_PLUS_TILDE_DASH,
      anon_sym_DASH_TILDE_PLUS,
      anon_sym_PLUS_TILDE_PLUS,
  [94] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(15), 1,
      sym_symbol,
    STATE(8), 1,
      sym_phrase,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [121] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(15), 1,
      sym_symbol,
    STATE(10), 1,
      sym_phrase,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [148] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(15), 1,
      sym_symbol,
    STATE(6), 1,
      sym_phrase,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [175] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(79), 1,
      sym_symbol,
    STATE(21), 1,
      sym_phrase,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [202] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(79), 1,
      sym_symbol,
    STATE(24), 1,
      sym_phrase,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [229] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(79), 1,
      sym_symbol,
    STATE(23), 1,
      sym_phrase,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [256] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      sym_copy_expr,
    ACTIONS(79), 1,
      sym_symbol,
    STATE(22), 1,
      sym_phrase,
    ACTIONS(11), 3,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
    STATE(2), 4,
      sym_at_expr,
      sym_branch_expr,
      sym_seq_expr,
      sym_measurement,
  [283] = 3,
    ACTIONS(81), 1,
      anon_sym_DASH_GT,
    STATE(20), 1,
      sym_branch_op,
    ACTIONS(45), 10,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_DASH_LT_DASH,
      anon_sym_PLUS_LT_DASH,
      anon_sym_DASH_LT_PLUS,
      anon_sym_PLUS_LT_PLUS,
      anon_sym_DASH_TILDE_DASH,
      anon_sym_PLUS_TILDE_DASH,
      anon_sym_DASH_TILDE_PLUS,
      anon_sym_PLUS_TILDE_PLUS,
  [302] = 3,
    ACTIONS(81), 1,
      anon_sym_DASH_GT,
    STATE(20), 1,
      sym_branch_op,
    ACTIONS(51), 10,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_DASH_LT_DASH,
      anon_sym_PLUS_LT_DASH,
      anon_sym_DASH_LT_PLUS,
      anon_sym_PLUS_LT_PLUS,
      anon_sym_DASH_TILDE_DASH,
      anon_sym_PLUS_TILDE_DASH,
      anon_sym_DASH_TILDE_PLUS,
      anon_sym_PLUS_TILDE_PLUS,
  [321] = 4,
    ACTIONS(81), 1,
      anon_sym_DASH_GT,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      sym_branch_op,
    ACTIONS(39), 8,
      anon_sym_DASH_LT_DASH,
      anon_sym_PLUS_LT_DASH,
      anon_sym_DASH_LT_PLUS,
      anon_sym_PLUS_LT_PLUS,
      anon_sym_DASH_TILDE_DASH,
      anon_sym_PLUS_TILDE_DASH,
      anon_sym_DASH_TILDE_PLUS,
      anon_sym_PLUS_TILDE_PLUS,
  [341] = 4,
    ACTIONS(81), 1,
      anon_sym_DASH_GT,
    ACTIONS(85), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      sym_branch_op,
    ACTIONS(39), 8,
      anon_sym_DASH_LT_DASH,
      anon_sym_PLUS_LT_DASH,
      anon_sym_DASH_LT_PLUS,
      anon_sym_PLUS_LT_PLUS,
      anon_sym_DASH_TILDE_DASH,
      anon_sym_PLUS_TILDE_DASH,
      anon_sym_DASH_TILDE_PLUS,
      anon_sym_PLUS_TILDE_PLUS,
  [361] = 2,
    ACTIONS(89), 2,
      sym_copy_expr,
      sym_symbol,
    ACTIONS(87), 5,
      anon_sym_LPAREN,
      anon_sym_AT,
      sym_null_expr,
      sym_sig_expr,
      sym_hash_expr,
  [373] = 1,
    ACTIONS(91), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_symbol,
  [380] = 3,
    ACTIONS(93), 1,
      anon_sym_COLON,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      aux_sym_places_repeat1,
  [390] = 3,
    ACTIONS(77), 1,
      sym_symbol,
    STATE(27), 1,
      sym_place,
    STATE(36), 1,
      sym_places,
  [400] = 3,
    ACTIONS(97), 1,
      anon_sym_COLON,
    ACTIONS(99), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      aux_sym_places_repeat1,
  [410] = 3,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    ACTIONS(102), 1,
      anon_sym_COLON,
    STATE(29), 1,
      aux_sym_places_repeat1,
  [420] = 2,
    ACTIONS(77), 1,
      sym_symbol,
    STATE(33), 1,
      sym_place,
  [427] = 2,
    ACTIONS(77), 1,
      sym_symbol,
    STATE(34), 1,
      sym_place,
  [434] = 1,
    ACTIONS(97), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [439] = 1,
    ACTIONS(104), 1,
      anon_sym_LBRACK,
  [443] = 1,
    ACTIONS(106), 1,
      sym_symbol,
  [447] = 1,
    ACTIONS(108), 1,
      anon_sym_COLON,
  [451] = 1,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 37,
  [SMALL_STATE(13)] = 74,
  [SMALL_STATE(14)] = 94,
  [SMALL_STATE(15)] = 121,
  [SMALL_STATE(16)] = 148,
  [SMALL_STATE(17)] = 175,
  [SMALL_STATE(18)] = 202,
  [SMALL_STATE(19)] = 229,
  [SMALL_STATE(20)] = 256,
  [SMALL_STATE(21)] = 283,
  [SMALL_STATE(22)] = 302,
  [SMALL_STATE(23)] = 321,
  [SMALL_STATE(24)] = 341,
  [SMALL_STATE(25)] = 361,
  [SMALL_STATE(26)] = 373,
  [SMALL_STATE(27)] = 380,
  [SMALL_STATE(28)] = 390,
  [SMALL_STATE(29)] = 400,
  [SMALL_STATE(30)] = 410,
  [SMALL_STATE(31)] = 420,
  [SMALL_STATE(32)] = 427,
  [SMALL_STATE(33)] = 434,
  [SMALL_STATE(34)] = 439,
  [SMALL_STATE(35)] = 443,
  [SMALL_STATE(36)] = 447,
  [SMALL_STATE(37)] = 451,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_phrase, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_phrase, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_measurement, 3, 0, 1),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_measurement, 3, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_at_expr, 5, 0, 5),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_at_expr, 5, 0, 5),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copland, 4, 0, 4),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_copland, 4, 0, 4),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_copland, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_copland, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seq_expr, 3, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_seq_expr, 3, 0, 2),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_expr, 3, 0, 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch_expr, 3, 0, 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_op, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_branch_op, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_places, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_places_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_places_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_places, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [110] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_copland(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "copland",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
